version: '2'
services:

  consul:
    image: "consul"
    hostname: "consul"
    container_name: "consul"
    command: "agent -server -bootstrap-expect=1 -data-dir=/consul/data -ui -client=0.0.0.0"
    volumes:
      - ~/docker/volumes/consul:/consul/data
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  vault:
    depends_on:
      - consul
    image: "vault"
    hostname: "vault"
    container_name: "vault"
    links:
      - "consul:consul"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./vault-config.hcl:/config/vault-config.hcl
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/vault-config.hcl
